name: VidPull
options:
  bundleIdPrefix: com.vidpull
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  VidPull:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vidpull.app
        INFOPLIST_FILE: Sources/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Sources/Resources/VidPull.entitlements
        PRODUCT_NAME: VidPull
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: Sources/Resources/Info.plist
      properties:
        CFBundleDisplayName: VidPull
        CFBundleName: VidPull
        CFBundleIdentifier: com.vidpull.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: VidPull
        LSMinimumSystemVersion: "13.0"
        NSHumanReadableCopyright: "Copyright © 2024. All rights reserved."
        NSPrincipalClass: NSApplication
        LSApplicationCategoryType: "public.app-category.utilities"
        NSSystemExtensionUsageDescription: "VidPull needs system extensions to provide enhanced functionality."
        NSAppleEventsUsageDescription: "VidPull uses Apple Events to interact with other applications."
        NSMenuBarExtraUsageDescription: "VidPull runs in the menu bar for quick access."
        NSPhotoLibraryUsageDescription: "VidPull may access your photo library to save downloaded media."
        NSPhotoLibraryAddUsageDescription: "VidPull needs permission to save downloaded media to your photo library."
        UIBackgroundModes:
          - fetch
          - processing
        LSUIElement: true
    entitlements:
      path: Sources/Resources/VidPull.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.network.client: true
    dependencies: []

schemes:
  VidPull:
    build:
      targets:
        VidPull: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
